#   Last updated November 2024
#
#   It really should use SwiftDialog instead of osascript. I'm not going to
#   rewrite it tho cause I don't have a need for it other than when I used it
#   for one mass offboarding in 2024.
#
#
####################################################################
#
# This script performs the following actions:
# 1. Throws up a dialog box and asks the user to enter a password
#       - If correct, continue...
#       - If incorrect, ask again until "cancel" is selected.
# 2. Retrieves the user's serial number from the system.
# 3. Uses the bearer token provided via Jamf $4
# 4. Use Jamf API to convert the serial number to a JamfID.
# 5. Sends a wipe command to the JamfID.

######################
######################
######################

# To increase security, the bearer token should be generated by IT, added to
# paremeter 4 in the jamf policy "Offboard Device." A bearer token is valid
# for 30 minutes. If un-commenting this code out and re-adding a hardcoded
# username/password, then you must also un-comment out line 148, which invalidates
# the generated bearer token after running the script.


# server and credential information
jamfProURL="URL"                        # Example "https://acme.jamfcloud.com"
username="username"                     # Enter the Jamf Pro username that has permissions to send wipe commands
password="password"                     # to computers.
# token=$4

# Request auth token.
authToken=$( /usr/bin/curl \
--request POST \
--silent \
--url "$jamfProURL/api/v1/auth/token" \
--user "$username:$password" )

# Parse auth token.
token=$( /usr/bin/plutil \
-extract token raw - <<< "$authToken" )

# echo "$token"

######################
######################
######################

# For running this script to remotely send wipe commands, rather than wiping the computer
# that is running the script
if [[ -n $@ ]]; then
   for serial_number in "$@"; do
        echo "Processing argument: $serial_number"

        # Convert serial number to JamfID.
        jamfId=$(curl -s --request GET \
            --url "$jamfProURL/JSSResource/computers/serialnumber/$serial_number" \
            --header "Authorization: Bearer $token" \
            --header "Accept: application/json" | sed -n 's/.*"general":{"id":\([0-9]*\).*/\1/p')

        # Check if jamfID is a number.
        if ! [[ "$jamfId" =~ ^[0-9]+$ ]]; then
            echo "Error converting the serial number into a Jamf ID."
            echo "Please make sure the Bearer Token is valid."
            exit 1
        fi

        echo "Jamf ID: $jamfId"

        # Send erase command to JamfID.
        response=$( /usr/bin/curl \
        --header "Authorization: Bearer $token" \
        --header "Content-Type: text/xml" \
        --request POST \
        --silent \
        --url "$jamfProURL/JSSResource/computercommands/command/EraseDevice/passcode/123456/id/$jamfId" )

        echo "$response" | sed -n 's/.*<p>\(.*\)<\/p>.*/\1/p'

   done
   echo "All serials have been sent a wipe command."
   exit 0
fi


######################
######################
######################


# Require password to be entered before proceeding.
password="eraseme"

while true; do
    # Prompt user for the password.
    user_password="$(osascript -e 'Tell application "System Events" to display dialog "Enter the password given to you by IT." default answer "" buttons {"OK", "Cancel"} default button "OK" with hidden answer' -e 'text returned of result' 2>/dev/null)"

    # Check if the user canceled the dialog.
    if [ $? -ne 0 ]; then
        osascript -e 'tell application "System Events" to display dialog "The erase of this computer was cancelled." buttons {"OK"} default button "OK"'
        echo "User cancelled the password input"
        exit 1
    fi

    # Check if the password is correct.
    if [ "$user_password" = $password ]; then
        # Run the policy or perform the desired action
        osascript -e 'tell application "System Events" to display dialog "Press OK to erase." buttons {"OK"} default button "OK"'
        ###########
        ###########
        ###########

        # Get the serial number of the Mac.
        serial_number=$(system_profiler SPHardwareDataType | awk '/Serial Number/{print $4}')
        echo "Serial Number: $serial_number"

        # Convert serial number to JamfID.
        jamfId=$(curl -s --request GET \
            --url "$jamfProURL/JSSResource/computers/serialnumber/$serial_number" \
            --header "Authorization: Bearer $token" \
            --header "Accept: application/json" | sed -n 's/.*"general":{"id":\([0-9]*\).*/\1/p')

        # Check if jamfID is a number.
        if ! [[ "$jamfId" =~ ^[0-9]+$ ]]; then
            echo "Error converting the serial number into a Jamf ID."
            echo "Please make sure the Bearer Token is valid."
            exit 1
        fi

        echo "Jamf ID: $jamfId"

        # exit 0

        # Send erase command to JamfID.
        response=$( /usr/bin/curl \
        --header "Authorization: Bearer $token" \
        --header "Content-Type: text/xml" \
        --request POST \
        --silent \
        --url "$jamfProURL/JSSResource/computercommands/command/EraseDevice/passcode/123456/id/$jamfId" )

        echo "$response" | sed -n 's/.*<p>\(.*\)<\/p>.*/\1/p'

        ######################
        ######################
        ######################

        # Invalidate auth token. Un-comment out if not passing
        /usr/bin/curl \
        --header "Authorization: Bearer $token" \
        --request POST \
        --silent \
        --url "$jamfProURL/api/v1/auth/invalidate-token"

        exit 0


        ###########
        ###########
        ###########
    else
        osascript -e 'tell application "System Events" to display dialog "Incorrect password. Please try again." buttons {"OK"} default button "OK"'
    fi
done
